
INSERT INTO tb_user (username, image, email, password, created_date) VALUES ('James Azevedo',     'https://cdn1.iconfinder.com/data/icons/diversity-avatars-volume-01-v2/64/hipster-man-white-512.png',                'jack@example.com',        '12345678', now());
INSERT INTO tb_user (username, image, email, password, created_date) VALUES ('Ryan Azevedo',     'https://cdn2.iconfinder.com/data/icons/diversity-avatars-volume-09/64/avatar-boler-suit-african-512.png',           'ryan@example.com',        '12345678', now());
INSERT INTO tb_user (username, image, email, password, created_date) VALUES ('Francis Rocha',    'https://cdn2.iconfinder.com/data/icons/diversity-v2-0-volume-01/64/accountant-asian-female-512.png',                'francis@example.com',     '12345678', now());
INSERT INTO tb_user (username, image, email, password, created_date) VALUES ('Anna Rocha',       'https://cdn2.iconfinder.com/data/icons/diversity-v2-0-volume-01/64/artist-asian-female-512.png',                    'anna@example.com',        '12345678', now());
INSERT INTO tb_user (username, image, email, password, created_date) VALUES ('Leonardo Silva',   'https://cdn0.iconfinder.com/data/icons/diversity-avatars-vol-4/64/hipster-man-caucasian-beard-512.png',             'leonardo@example.com',    '12345678', now());
INSERT INTO tb_user (username, image, email, password, created_date) VALUES ('Raquel Silva',     'https://cdn0.iconfinder.com/data/icons/diversity-avatars-vol-4/64/woman-round-glasses-hair-bun-512.png',            'raquel@example.com',      '12345678', now());
INSERT INTO tb_user (username, image, email, password, created_date) VALUES ('Lyanne Almeida',   'https://cdn2.iconfinder.com/data/icons/health-care-and-first-responders/64/ems-black-female-coronavirus-512.png',   'lyanne@example.com',      '12345678', now());
INSERT INTO tb_user (username, image, email, password, created_date) VALUES ('Ellioth Almeida',  'https://cdn0.iconfinder.com/data/icons/diversity-v2-0-volume-08/64/asian-beatnik-glasses-goatee-manbun-512.png',    'ellioth@example.com',     '12345678', now());
INSERT INTO tb_user (username, image, email, password, created_date) VALUES ('Apollo Santos',    'https://cdn0.iconfinder.com/data/icons/diversity-avatars-vol-4/64/farmer-man-caucasian-overalls-512.png',           'apollo@example.com',      '12345678', now());
INSERT INTO tb_user (username, image, email, password, created_date) VALUES ('Gutierry Santos',  'https://cdn2.iconfinder.com/data/icons/health-care-and-first-responders/64/doctor-asian-male-coronavirus-512.png',  'gutierry@example.com',    '12345678', now());
INSERT INTO tb_user (username, image, email, password, created_date) VALUES ('Victória Lima',    'https://cdn1.iconfinder.com/data/icons/basic-ui-element-2-2-line/512/Basic_UI_Elements_-_2.1_-_line-11-256.png',    'victoria@example.com',    '12345678', now());
INSERT INTO tb_user (username, image, email, password, created_date) VALUES ('Elenora Lima',     'https://cdn1.iconfinder.com/data/icons/basic-ui-element-2-2-line/512/Basic_UI_Elements_-_2.1_-_line-11-256.png',    'elenora@example.com',     '12345678', now());
INSERT INTO tb_user (username, image, email, password, created_date) VALUES ('Pietra Silva',     'https://cdn1.iconfinder.com/data/icons/basic-ui-element-2-2-line/512/Basic_UI_Elements_-_2.1_-_line-11-256.png',    'pietra@example.com',      '12345678', now());
INSERT INTO tb_user (username, image, email, password, created_date) VALUES ('Rafael Silva',     'https://cdn1.iconfinder.com/data/icons/basic-ui-element-2-2-line/512/Basic_UI_Elements_-_2.1_-_line-11-256.png',    'rafael@example.com',      '12345678', now());
INSERT INTO tb_user (username, image, email, password, created_date) VALUES ('Mary Gomes',       'https://cdn1.iconfinder.com/data/icons/basic-ui-element-2-2-line/512/Basic_UI_Elements_-_2.1_-_line-11-256.png',    'mary@example.com',        '12345678', now());
INSERT INTO tb_user (username, image, email, password, created_date) VALUES ('Felipe Santana',   'https://cdn1.iconfinder.com/data/icons/basic-ui-element-2-2-line/512/Basic_UI_Elements_-_2.1_-_line-11-256.png',    'felipe@example.com',      '12345678', now());
INSERT INTO tb_user (username, image, email, password, created_date) VALUES ('Lorenzo Santos',   'https://cdn1.iconfinder.com/data/icons/basic-ui-element-2-2-line/512/Basic_UI_Elements_-_2.1_-_line-11-256.png',    'lorenzo@example.com',     '12345678', now());
INSERT INTO tb_user (username, image, email, password, created_date) VALUES ('Elizabeth Valle',  'https://cdn2.iconfinder.com/data/icons/health-care-and-first-responders/64/ems-black-female-coronavirus-512.png',   'elizabeth@example.com',   '12345678', now());
INSERT INTO tb_user (username, image, email, password, created_date) VALUES ('Helena Lima',      'https://cdn2.iconfinder.com/data/icons/diversity-v2-0-volume-01/64/accountant-asian-female-512.png',                'helena@example.com',      '12345678', now());
INSERT INTO tb_user (username, image, email, password, created_date) VALUES ('Albert Almeida',   'https://cdn2.iconfinder.com/data/icons/diversity-avatars-volume-09/64/avatar-boler-suit-african-512.png',           'albert@example.com',      '12345678', now());
INSERT INTO tb_user (username, image, email, password, created_date) VALUES ('Joseph Almeida',   'https://cdn0.iconfinder.com/data/icons/diversity-avatars-vol-4/64/farmer-man-caucasian-overalls-512.png',           'joseph@example.com',      '12345678', now());
INSERT INTO tb_user (username, image, email, password, created_date) VALUES ('Igniz Javier',     'https://cdn0.iconfinder.com/data/icons/diversity-avatars-vol-4/64/hipster-man-caucasian-beard-512.png',             'igniz@example.com',       '12345678', now());
INSERT INTO tb_user (username, image, email, password, created_date) VALUES ('Billy Castro',     'https://cdn0.iconfinder.com/data/icons/diversity-v2-0-volume-08/64/asian-beatnik-glasses-goatee-manbun-512.png',    'billy@example.com',       '12345678', now());
INSERT INTO tb_user (username, image, email, password, created_date) VALUES ('Luccas Matos',     'https://cdn1.iconfinder.com/data/icons/diversity-avatars-volume-01-v2/64/hipster-man-white-512.png',                'luccas@example.com',      '12345678', now());
INSERT INTO tb_user (username, image, email, password, created_date) VALUES ('Angêlica Pinho',   'https://cdn2.iconfinder.com/data/icons/diversity-v2-0-volume-01/64/artist-asian-female-512.png',                    'angelica@example.com',    '12345678', now());
INSERT INTO tb_user (username, image, email, password, created_date) VALUES ('Joseph Castro',    'https://cdn2.iconfinder.com/data/icons/health-care-and-first-responders/64/doctor-asian-male-coronavirus-512.png',  'joseph@example.com',      '12345678', now());
INSERT INTO tb_user (username, image, email, password, created_date) VALUES ('Osvald Castro',    'https://cdn1.iconfinder.com/data/icons/basic-ui-element-2-2-line/512/Basic_UI_Elements_-_2.1_-_line-11-256.png',    'osvald@example.com',      '12345678', now());
INSERT INTO tb_user (username, image, email, password, created_date) VALUES ('Joel Castro',      'https://cdn1.iconfinder.com/data/icons/basic-ui-element-2-2-line/512/Basic_UI_Elements_-_2.1_-_line-11-256.png',    'joel@example.com',        '12345678', now());
INSERT INTO tb_user (username, image, email, password, created_date) VALUES ('Rose Santana',     'https://cdn1.iconfinder.com/data/icons/basic-ui-element-2-2-line/512/Basic_UI_Elements_-_2.1_-_line-11-256.png',    'rose@example.com',        '12345678', now());

INSERT INTO tb_category (name, description) VALUES ('Meio Ambiente', 'O Meio Ambiente envolve os interesses regionais com as causas ambientais, algumas atribuições relacionadas ao meio ambiente são: a preservação de biomas, garantia dos recursos hídricos e florestais e o uso sustentável de ecossistemas.');
INSERT INTO tb_category (name, description) VALUES ('Agricultura', 'A Agricultura abrange o conjunto de práticas e atividades voltadas para o cultivo de plantas e a criação de animais com o objetivo de produzir alimentos, fibras, medicinais e outros produtos. Envolve processos como a preparação do solo, plantio, manejo de pragas, colheita e distribuição dos produtos agrícolas.');
INSERT INTO tb_category (name, description) VALUES ('Botânica', 'A Botânica é o ramo da Biologia que se dedica ao estudo das plantas. Ela abrange a fisiologia, morfologia, ecologia vegetal e taxonomia, ou seja, todas as características, interações e funcionamento das plantas.');
INSERT INTO tb_category (name) VALUES ('Moradia');
INSERT INTO tb_category (name) VALUES ('Arquitetura');
INSERT INTO tb_category (name) VALUES ('Geografia');
INSERT INTO tb_category (name) VALUES ('Hidrografia');
INSERT INTO tb_category (name) VALUES ('Biologia');
INSERT INTO tb_category (name) VALUES ('Educação');
INSERT INTO tb_category (name) VALUES ('História');
INSERT INTO tb_category (name) VALUES ('Cultura');
INSERT INTO tb_category (name) VALUES ('Ciência');
INSERT INTO tb_category (name) VALUES ('Tecnologia');
INSERT INTO tb_category (name) VALUES ('Segurança');
INSERT INTO tb_category (name) VALUES ('Economia');
INSERT INTO tb_category (name) VALUES ('Transporte');


INSERT INTO tb_project (user_id, created_date, title, description, image) VALUES (1,   now(),  'Agrobairros',                         'Os projetos urbanos que combinam casas e áreas de produção de alimentos solucionam duas demandas de quem vive em cidades: um contato maior com a natureza e a proximidade com a produção de alimentos – o que gera menos impacto ambiental e, muitas vezes, acesso à comida produzida de maneira mais saudável e sustentável. Nesta publicação, veja mais sobre quais conteúdos didáticos, eventos e atividades que estão relacionadas aos Agrobairros em Caxias', 'https://www.graphikmaquetas.com.ar/val8.jpg');
INSERT INTO tb_project (user_id, created_date, title, description, image) VALUES (2,   now(),  'Coleta e Filtragem de Água',          'Os projetos de coleta e filtragem de água visão prover a criação de estruturas que possam sar facilmente instaladas em diversos locais da cidade permitindo também que a água da chuva seja coletada, filtrada e armazenada para os períodos mais secos, auxiliando na gestão sustentável da água. Neste projeto, veja mais sobre quais conteúdos didáticos, eventos e atividades que estão relacionadas a Coleta e Filtragem de Água em Caxias', 'https://img.freepik.com/premium-vector/water-drop-shape-blue-water-drop-logo-design-water-oil-drop_275352-810.jpg');
INSERT INTO tb_project (user_id, created_date, title, description, image) VALUES (2,   now(),  'Reflorestamento',                     'Neste projeto, veja mais sobre quais conteúdos didáticos, eventos e atividades que estão relacionadas ao Reflorestamento em Caxias', 'https://sitesustentavel.com.br/wp-content/uploads/2019/05/sh_reflorestamento_790269046.jpg');
INSERT INTO tb_project (user_id, created_date, title, description, image) VALUES (3,   now(),  'Arquitetura Acessível e Sutentável',  'Os projetos de moradia que envolvem uma arquitetura de preço acessível, uma alta velocidade na produção e um baixo impacto no meito ambiente podem ser uma solução prática para o problema de pessoas em situação de vunerabilidade com moradia. Neste projeto, veja mais sobre quais conteúdos didáticos, eventos e atividades que estão relacionadas a Arquitetura Acessível e Sustentável em Caxias', 'https://www.aubicon.com.br/wp-content/uploads/2021/03/04_arq_sustentavel_blog_15.jpg');
INSERT INTO tb_project (user_id, created_date, title, description, image) VALUES (4,   now(),  'Reurbanização',                       'Os projetos de reurbanização são iram pertimitir a reorganização do espaço urbano e a implantação da infraestrutura necessária em um determinado contexto. Nesta publicação, veja mais sobre quais conteúdos didáticos, eventos e atividades que estão relacionadas a Reurbanização em Caxias', 'https://files.prokerala.com/news/photos/imgs/1024/telangana-mobility-valley-1522957.jpg');
INSERT INTO tb_project (user_id, created_date, title, description, image) VALUES (6,   now(),  'Presevação de Bairros Históricos',    'Neste projeto, veja mais sobre quais conteúdos didáticos, eventos e atividades que estão relacionadas a Preservação de Bairros Históricos em Caxias', 'https://3.bp.blogspot.com/-2VlbdH8dBu0/Ugws24hLLlI/AAAAAAAABD8/1UDgWHfQjg4/s1600/SAM_2660.JPG');
INSERT INTO tb_project (user_id, created_date, title, description, image) VALUES (7,   now(),  'Desenvolvimento Cultural',            'Neste projeto, veja mais sobre quais conteúdos didáticos, eventos e atividades que estão relacionadas ao Desenvolvimento Cultural em Caxias', 'https://maken.wikiwijs.nl/generated/s960x720_a8b0a9ba449553dffd7e56bcca7286970445c6e3.jpg');
INSERT INTO tb_project (user_id, created_date, title, description, image) VALUES (7,   now(),  'Hitória da Cidade',                   'Neste projeto, veja mais sobre quais conteúdos didáticos, eventos e atividades que estão relacionadas a História da Cidade de Caxias', 'https://wallpaperaccess.com/full/6741861.jpg');
INSERT INTO tb_project (user_id, created_date, title, description, image) VALUES (13,  now(),  'Literatura Regional',                 'Neste projeto, veja mais sobre quais conteúdos didáticos, eventos e atividades que estão relacionadas a Literatura Regional em Caxias', 'https://www.lifeder.com/wp-content/uploads/2020/03/concepto-literatura-libros-min-1.jpg');
INSERT INTO tb_project (user_id, created_date, title, description, image) VALUES (2,   now(),  'Energias Renováveis',                 'Neste projeto, veja mais sobre quais conteúdos didáticos, eventos e atividades que estão relacionadas as Energias Renováveis em Caxias', 'https://sitesustentavel.com.br/wp-content/uploads/2019/05/sh_energia-renovavel_553614883.jpg');
INSERT INTO tb_project (user_id, created_date, title, description, image) VALUES (5,   now(),  'Inovação Tecnológica na Educação',    'Neste projeto, veja mais sobre quais conteúdos didáticos, eventos e atividades que estão relacionadas a Invovação Tecnológica na Educação em Caxias', 'https://neetable.com/img/blog/blog-inner/the-role-of-future-education/the-role-of-future-education.jpg');
INSERT INTO tb_project (user_id, created_date, title, description, image) VALUES (9,   now(),  'Epreendedorismo e Microempresas',     'Neste projeto, veja mais sobre quais conteúdos didáticos, eventos e atividades que estão relacionadas a Empreendedorismos e Microempresas em Caxias', 'https://www.dashboarddesign.com.br/wp-content/uploads/2020/01/shutterstock_780647377.jpg');
INSERT INTO tb_project (user_id, created_date, title, description, image) VALUES (9,   now(),  'Educação Financeira e Investimentos', 'Neste projeto, veja mais sobre quais conteúdos didáticos, eventos e atividades que estão relacionadas a Educação Fianceira e Investimentos em Caxias', 'https://www.dashboarddesign.com.br/wp-content/uploads/2020/01/shutterstock_780647377.jpg');
INSERT INTO tb_project (user_id, created_date, title, description, image) VALUES (11,  now(),  'Bairros Comerciais',                  'Neste projeto, veja mais sobre quais conteúdos didáticos, eventos e atividades que estão relacionadas a Bairros Comerciais em Caxias', 'https://files.prokerala.com/news/photos/imgs/1024/telangana-mobility-valley-1522957.jpg');
INSERT INTO tb_project (user_id, created_date, title, description, image) VALUES (8,   now(),  'Educação Política',                   'Neste projeto, veja mais sobre quais conteúdos didáticos, eventos e atividades que estão relacionadas a Educação Política em Caxias', 'http://portal.metodista.br/reportagens-especiais/reportagens/2014/imagens-1/grupo2m/TENTATIVA.jpg');
INSERT INTO tb_project (user_id, created_date, title, description, image) VALUES (2,   now(),  'Transporte Ferroviário Passageiro',   'Neste projeto, veja mais sobre quais conteúdos didáticos, eventos e atividades que estão relacionadas a Transporte Ferroviário em Caxias', 'https://wallpaperaccess.com/full/2064090.jpg');
INSERT INTO tb_project (user_id, created_date, title, description, image) VALUES (3,   now(),  'Segurança Escolar',                   'Neste projeto, veja mais sobre quais conteúdos didáticos, eventos e atividades que estão relacionadas a Segurança Escolar em Caxias', 'https://www.orcali.com.br/wp-content/uploads/2021/07/blog.png');
INSERT INTO tb_project (user_id, created_date, title, description, image) VALUES (3,   now(),  'Segurança Comercial',                 'Neste projeto, veja mais sobre quais conteúdos didáticos, eventos e atividades que estão relacionadas a Segurança Comercial em Caxias', 'https://www.generall.com.br/wp-content/uploads/elementor/thumbs/seguranca-patrimonial-1-px2rpyhr8687jo5dgwtt3nmiygdifjq5bp96cbl7v4.jpg');

INSERT INTO tb_event (project_id, user_id, event_date, created_date, event_status, image, title, description) VALUES (1, 1,   '2025-01-03',   now(),   'PLANEJANDO',   'https://cdn1.iconfinder.com/data/icons/business-vivid-vol-2/256/Seminar-1024.png',  'Seminário sobre a distribuição de alimentos nos Agrobairros em Caxias', 'Este evento trata-se de um seminário sobre a distribuição de alimentos nos Agrobairros em Caxias. O Evento reunirá especialistas, agricultores locais, residentes nos bairros envolvidos e interessados na temática para discutir as práticas e políticas que possam garantir uma entrega eficiente e justa de alimentos nas áreas dos Agrobairros Caxienses. Será uma oportunidade para aprender, trocar experiências e buscar soluções inovadoras para melhorar a cadeia de distribuição, impactando positivamente a segurança alimentar e a qualidade de vida da comunidade.');
INSERT INTO tb_event (project_id, user_id, event_date, created_date, event_status, image, title, description) VALUES (1, 1,   '2025-01-09',   now(),   'PLANEJANDO',   'https://cdn2.iconfinder.com/data/icons/career-advancement-4/512/Practice-1024.png',  'Atividade prática para estabelecimento de hortas comunitárias no bairro Nova Caxias', 'O evento é uma iniciativa que visa transformar espaços urbanos subutilizados em hortas comunitárias produtivas no bairro Nova Caxias. Este evento prático reunirá moradores do bairro para colaborar na criação de hortas que não só fornecerão alimentos saudáveis, mas também promoverão a integração social, a educação ambiental e a sustentabilidade.');
INSERT INTO tb_event (project_id, user_id, event_date, created_date, event_status, image, title, description) VALUES (1, 2,   '2025-02-15',   now(),   'PLANEJANDO',   'https://cdn2.iconfinder.com/data/icons/system-filled-outline/64/warning-danger-system-icon-512.png',     'Palestra sobre riscos e cuidados com pragas nas hortas em Agrobairros de Caxias', 'Este evento é uma iniciativa educativa voltada para os moradores de Agrobairros que desejam aprender mais sobre como proteger suas hortas das pragas mais comuns. Este evento visa fornecer conhecimentos práticos e teóricos sobre a identificação, prevenção e controle de pragas, promovendo a conscientização de uma agricultura urbana mais saudável e sustentável.');
INSERT INTO tb_event (project_id, user_id, event_date, created_date, event_status, image, title, description) VALUES (1, 2,   '2025-03-11',   now(),   'PLANEJANDO',   'https://cdn-icons-png.flaticon.com/512/9912/9912471.png',  'Apresentação e debate dos dados periódicos sobre as colheitas nos Agrobairros em Caxias', 'O evento é uma oportunidade para os moradores, gestores públicos e interessados se reunirem para analisar e discutir os dados mais recentes sobre o desenvolvimento das colheitas dos Agrobairros na cidade. Este evento visa promover a transparência, a participação comunitária e a tomada de decisões informadas com base em dados concretos.');
INSERT INTO tb_event (project_id, user_id, event_date, created_date, event_status, image, title, description) VALUES (1, 3,   '2025-04-18',   now(),   'PROGRAMADO',   'https://cdn0.iconfinder.com/data/icons/smart-technology-malibu-volume-1/128/intelligent-power-512.png',  'Criação de soluções para automatizar a produção de alimentos nos Agrobairros em Caxias', 'O evento objetiva reunir especialistas, agricultores urbanos e entusiastas da tecnologia para discutir e desenvolver soluções inovadoras que automatizem a produção de alimentos nos Agrobairros de Caxias. Este evento busca promover a adoção de tecnologias avançadas para aumentar a eficiência, sustentabilidade e produtividade das hortas urbanas.');
INSERT INTO tb_event (project_id, user_id, event_date, created_date, event_status, image, title, description) VALUES (1, 3,   '2024-10-12',   now(),   'PROGRAMADO',   'https://cdn-icons-png.flaticon.com/512/4730/4730760.png',  'Videoconfêrencia sobre plantio de cereais na Vila Conquista de Caxias', 'Este evento promove o compartilhamento de conhecimentos e práticas sobre o cultivo de cereais em ambientes urbanos. Este evento online reunirá especialistas, agricultores urbanos e interessados para discutir técnicas, desafios e inovações no plantio de cereais, promovendo a sustentabilidade e a segurança alimentar na Vila Conquista');
INSERT INTO tb_event (project_id, user_id, event_date, created_date, event_status, image, title, description) VALUES (1, 4,   '2024-10-20',   now(),   'PROGRAMADO',   'https://cdn0.iconfinder.com/data/icons/business-situations-flat-1/64/annual-report-graph-summary-company-1024.png',  'Produção de relatórios sobre benefícios dos Agrobairros na economia de Caxias', 'O evento que conta com a participação de especialistas, gestores públicos, economistas e membros da comunidade busca analisar e documentar atráves da produção de relatórios os impactos econômicos positivos dos Agrobairros na cidade de Caxias. Este evento busca promover a compreensão e a valorização da agricultura urbana como um motor de desenvolvimento econômico.');
INSERT INTO tb_event (project_id, user_id, event_date, created_date, event_status, image, title, description) VALUES (1, 4,   '2024-11-03',   now(),   'PROGRAMADO',   'https://cdn1.iconfinder.com/data/icons/business-vivid-vol-2/256/Seminar-1024.png',  'Seminário sobre a conservação de alimentos nos Agrobairros em Caxias', 'Este evento é um seminário sobre a Conservação de Alimentos em Agrobairros é uma iniciativa educativa que objetiva capacitar os moradores e agricultores urbanos sobre as melhores práticas e tecnologias para a conservação de alimentos. Este evento reunirá especialistas, técnicos e a comunidade para discutir métodos eficazes de preservação, garantindo a qualidade e a segurança dos alimentos produzidos nos Agrobairros.');
INSERT INTO tb_event (project_id, user_id, event_date, created_date, event_status, image, title, description) VALUES (1, 4,   '2024-11-09',   now(),   'ADIADO',       'https://cdn2.iconfinder.com/data/icons/career-advancement-4/512/Practice-1024.png',  'Atividade prática para estabelecimento de hortas comunitárias no bairro Trizidela', 'O evento é uma iniciativa que visa transformar espaços urbanos subutilizados em hortas comunitárias produtivas no bairro Trizidela. Este evento prático reunirá moradores do bairro para colaborar na criação de hortas que não só fornecerão alimentos saudáveis, mas também promoverão a integração social, a educação ambiental e a sustentabilidade.');
INSERT INTO tb_event (project_id, user_id, event_date, created_date, event_status, image, title, description) VALUES (1, 5,   '2024-02-15',   now(),   'ADIADO',       'https://cdn2.iconfinder.com/data/icons/system-filled-outline/64/warning-danger-system-icon-512.png',     'Palestra sobre cuidados com agrotóxicos nas hortas em Agrobairros de Caxias', 'A palestra cuidados no uso de agrotóxicos nas hortas dos agrobairros de Caxias é um evento educativa destinado a informar e capacitar os moradores e agricultores urbanos sobre o uso seguro e responsável de agrotóxicos. Este evento visa promover a saúde, a segurança e a sustentabilidade nas práticas agrícolas dos Agrobairros.');
INSERT INTO tb_event (project_id, user_id, event_date, created_date, event_status, image, title, description) VALUES (1, 5,   '2024-03-11',   now(),   'FINALIZADO',   'https://cdn-icons-png.flaticon.com/512/9912/9912471.png',  'Apresentação e debate dos dados periódicos sobre a distribuição de alimentos dos Agrobairros em Caxias', 'O evento é uma oportunidade para os moradores, gestores públicos e interessados se reunirem para analisar e discutir os dados mais recentes sobre o desenvolvimento da distribuição de alimentos dos Agrobairros na cidade. Este evento visa promover a transparência, a participação comunitária e a tomada de decisões informadas com base em dados concretos.');
INSERT INTO tb_event (project_id, user_id, event_date, created_date, event_status, image, title, description) VALUES (1, 5,   '2024-04-18',   now(),   'FINALIZADO',   'https://cdn0.iconfinder.com/data/icons/smart-technology-malibu-volume-1/128/intelligent-power-512.png',              'Criação de soluções para capacitar moradores no manuseio de hortas nos Agrobairros em Caxias', 'O evento objetiva reunir especialistas, agricultores urbanos e entusiastas da tecnologia para discutir e desenvolver soluções inovadoras para capacitação de moradores no manuseio de hortas nos Agrobairros de Caxias. Este evento busca promover a adoção de novas ideias para aumentar a eficiência, sustentabilidade e produtividade das hortas urbanas.');
INSERT INTO tb_event (project_id, user_id, event_date, created_date, event_status, image, title, description) VALUES (1, 6,   '2024-05-12',   now(),   'FINALIZADO',   'https://cdn-icons-png.flaticon.com/512/4730/4730760.png',                                                            'Videoconfêrencia sobre plantio de cereais no Morro do Alecrim de Caxias', 'Este evento promove o compartilhamento de conhecimentos e práticas sobre o cultivo de cereais em ambientes urbanos. Este evento online reunirá especialistas, agricultores urbanos e interessados para discutir técnicas, desafios e inovações no plantio de cereais, promovendo a sustentabilidade e a segurança alimentar na Vila Conquista');
INSERT INTO tb_event (project_id, user_id, event_date, created_date, event_status, image, title, description) VALUES (1, 6,   '2024-06-20',   now(),   'FINALIZADO',   'https://cdn0.iconfinder.com/data/icons/business-situations-flat-1/64/annual-report-graph-summary-company-1024.png',  'Produção de relatórios sobre o auxílio dos Agrobairros na segurança alimentar de Caxias', 'O evento que conta com a participação de especialistas, gestores públicos, economistas e membros da comunidade busca analisar e documentar atráves da produção de relatórios os impactos positivos dos Agrobairros na segurança alimentar da cidade de Caxias. Este evento busca promover a compreensão e a valorização da agricultura urbana como um auxiliar na vida dos mais vulneráveis.');
INSERT INTO tb_event (project_id, user_id, event_date, created_date, event_status, image, title, description) VALUES (1, 6,   '2023-01-03',   now(),   'FINALIZADO',   'https://cdn1.iconfinder.com/data/icons/business-vivid-vol-2/256/Seminar-1024.png',                                       'Seminário 3 sobre os Agrobairros em Caxias', 'O evento "Seminário 3 sobre os Agrobairros em Caxias" trata-se de um seminário sobre os Agrobairros em Caxias. O Evento reunirá especialistas, agricultores locais, residentes nos bairros envolvidos e interessados na temática para discutir as práticas e políticas sobre os Agrobairros Caxienses. Será uma oportunidade para aprender, trocar experiências e buscar soluções inovadoras.');
INSERT INTO tb_event (project_id, user_id, event_date, created_date, event_status, image, title, description) VALUES (1, 7,   '2023-01-09',   now(),   'INDEFINIDO',   'https://cdn2.iconfinder.com/data/icons/career-advancement-4/512/Practice-1024.png',                                      'Atividade prática 3 sobre os Agrobairros em Caxias', 'O evento "Atividade prática 3 sobre os Agrobairros em Caxias" é uma iniciativa que visa implementar medidas práticas e técnicas em benefício dos Agrobairros em Caxias. Este evento prático reunirá moradores do bairro para colaborar na criação de hortas que não só fornecerão alimentos saudáveis, mas também promoverão a integração social, a educação ambiental e a sustentabilidade.');
INSERT INTO tb_event (project_id, user_id, event_date, created_date, event_status, image, title, description) VALUES (1, 7,   '2023-02-15',   now(),   'INDEFINIDO',   'https://cdn2.iconfinder.com/data/icons/system-filled-outline/64/warning-danger-system-icon-512.png',                 'Palestra 3 sobre os Agrobairros em Caxias', 'O evento "Palestra 3 sobre os Agrobairros em Caxias" é uma iniciativa educativa voltada para os moradores de Agrobairros que desejam aprender mais sobre detalhes sobre Agrobairros. Este evento visa fornecer conhecimentos práticos e teóricos e a conscientização de uma agricultura urbana mais saudável e sustentável.');
INSERT INTO tb_event (project_id, user_id, event_date, created_date, event_status, image, title, description) VALUES (1, 7,   '2023-03-11',   now(),   'INDEFINIDO',   'https://cdn-icons-png.flaticon.com/512/9912/9912471.png',                                                            'Apresentação e debate dos dados periódicos 3 sobre os Agrobairros em Caxias', 'O evento "Apresentação e debate dos dados periódicos 3 sobre os Agrobairros em Caxias" é uma oportunidade para os moradores, gestores públicos e interessados se reunirem para analisar e discutir os dados mais recentes sobre o desenvolvimento sobre os Agrobairros na cidade. Este evento visa promover a transparência, a participação comunitária e a tomada de decisões informadas com base em dados concretos.');
INSERT INTO tb_event (project_id, user_id, event_date, created_date, event_status, image, title, description) VALUES (1, 8,   '2023-04-18',   now(),   'CANCELADO',    'https://cdn0.iconfinder.com/data/icons/smart-technology-malibu-volume-1/128/intelligent-power-512.png',              'Criação de soluções 3 sobre os Agrobairros em Caxias', 'O evento "Criação de soluções 3 sobre os Agrobairros em Caxias" objetiva reunir especialistas, agricultores urbanos e entusiastas da tecnologia para discutir e desenvolver soluções inovadoras em prol dos Agrobairros de Caxias. Este evento busca promover a adoção de novas ideias para aumentar a eficiência, sustentabilidade e produtividade das hortas urbanas.');
INSERT INTO tb_event (project_id, user_id, event_date, created_date, event_status, image, title, description) VALUES (1, 8,   '2023-05-12',   now(),   'PLANEJANDO',   'https://cdn-icons-png.flaticon.com/512/4730/4730760.png',                                                            'Videoconfêrencia 3 sobre os Agrobairros em Caxias', 'O evento "Videoconfêrencia 3 sobre os Agrobairros em Caxias" promove o compartilhamento de conhecimentos e práticas sobre Agrobairros. Este evento online reunirá especialistas, agricultores urbanos e interessados para discutir técnicas, desafios e inovações, promovendo a sustentabilidade e a segurança alimentar');
INSERT INTO tb_event (project_id, user_id, event_date, created_date, event_status, image, title, description) VALUES (1, 8,   '2023-06-20',   now(),   'PLANEJANDO',   'https://cdn0.iconfinder.com/data/icons/business-situations-flat-1/64/annual-report-graph-summary-company-1024.png',  'Produção de relatórios 3 sobre os Agrobairros em Caxias', 'O evento que conta com a participação de especialistas, gestores públicos, economistas e membros da comunidade busca analisar e documentar atráves da produção de relatórios sobre os Agrobairros na cidade de Caxias. Este evento busca promover a compreensão e a valorização da agricultura urbana.');
INSERT INTO tb_event (project_id, user_id, event_date, created_date, event_status, image, title, description) VALUES (2, 3,   '2024-01-03',   now(),   'PLANEJANDO',   'https://cdn1.iconfinder.com/data/icons/business-vivid-vol-2/256/Seminar-1024.png',                                        'Seminário 1 sobre a Coleta e Filtragem de Água em Caxias', 'O evento "Seminário 1 sobre a Coleta e Filtragem de Água em Caxias" trata-se de um seminário sobre a Coleta e Filtragem de Água em Caxias. O Evento reunirá especialistas, hidrógrafos locais, residentes nos bairros envolvidos e interessados na temática para discutir as práticas e políticas acerca do assunto. Será uma oportunidade para aprender, trocar experiências e buscar soluções inovadoras.');
INSERT INTO tb_event (project_id, user_id, event_date, created_date, event_status, image, title, description) VALUES (2, 3,   '2024-01-09',   now(),   'PLANEJANDO',   'https://cdn2.iconfinder.com/data/icons/career-advancement-4/512/Practice-1024.png',                                       'Atividade prática 1 sobre a Coleta e Filtragem de Água em Caxias', 'O evento "Atividade prática 1 sobre a Coleta e Filtragem de Água em Caxias" é uma iniciativa que visa implementar medidas práticas e técnicas em benefício da Coleta e Filtragem de Água em Caxias. Este evento prático reunirá moradores do bairro para colaborar nos processos práticos que promoverão a integração social, a educação técnica e a multidisciplinaridade.');
INSERT INTO tb_event (project_id, user_id, event_date, created_date, event_status, image, title, description) VALUES (2, 4,   '2024-02-15',   now(),   'PROGRAMADO',   'https://cdn2.iconfinder.com/data/icons/system-filled-outline/64/warning-danger-system-icon-512.png',                  'Palestra 1 sobre a Coleta e Filtragem de Água em Caxias', 'O evento "Palestra 1 sobre a Coleta e Filtragem de Água em Caxias" é uma iniciativa educativa voltada para os moradores que desejam aprender mais sobre detalhes sobre a Coleta e Filtragem de Água. Este evento visa fornecer conhecimentos práticos e teóricos, concientizando os participantes da importância da Coleta e Filtragem de Água.');
INSERT INTO tb_event (project_id, user_id, event_date, created_date, event_status, image, title, description) VALUES (2, 4,   '2024-03-11',   now(),   'PROGRAMADO',   'https://cdn-icons-png.flaticon.com/512/9912/9912471.png',                                                            'Apresentação e debate dos dados periódicos 1 sobre a Coleta e Filtragem de Água em Caxias', 'O evento "Apresentação e debate dos dados periódicos 1 sobre a Coleta e Filtragem de Água em Caxias" é uma oportunidade para os moradores, gestores públicos e interessados se reunirem para analisar e discutir os dados mais recentes sobre o desenvolvimento sobre a Coleta e Filtragem de Água na cidade. Este evento visa promover a transparência, a participação comunitária e a tomada de decisões informadas com base em dados concretos.');
INSERT INTO tb_event (project_id, user_id, event_date, created_date, event_status, image, title, description) VALUES (2, 5,   '2024-04-18',   now(),   'PROGRAMADO',   'https://cdn0.iconfinder.com/data/icons/smart-technology-malibu-volume-1/128/intelligent-power-512.png',               'Criação de soluções para a Coleta e Filtragem de Água dos rios em Caxias', 'O evento "Criação de soluções para a Coleta e Filtragem de Água dos rios em Caxias" objetiva reunir especialistas, moradores e entusiastas da inovação para discutir e desenvolver soluções inovadoras em prol da Coleta e Filtragem de Água de Caxias. Este evento busca promover a adoção de novas ideias que foquem na eficiência e praticidade.');
INSERT INTO tb_event (project_id, user_id, event_date, created_date, event_status, image, title, description) VALUES (2, 5,   '2024-05-12',   now(),   'PROGRAMADO',   'https://cdn-icons-png.flaticon.com/512/4730/4730760.png',                                                             'Videoconfêrencia 1 sobre a Coleta e Filtragem de Água em Caxias', 'O evento "Videoconfêrencia 1 sobre a Coleta e Filtragem de Água em Caxias" promove o compartilhamento de conhecimentos e práticas sobre a Coleta e Filtragem de Água. Este evento online reunirá especialistas, moradores urbanos e interessados para discutir técnicas, desafios e inovações');
INSERT INTO tb_event (project_id, user_id, event_date, created_date, event_status, image, title, description) VALUES (2, 6,   '2024-06-20',   now(),   'ADIADO',       'https://cdn0.iconfinder.com/data/icons/business-situations-flat-1/64/annual-report-graph-summary-company-1024.png',   'Produção de relatórios 1 sobre a Coleta e Filtragem de Água em Caxias', 'O evento "Produção de relatórios 1 sobre a Coleta e Filtragem de Água em Caxias" que conta com a participação de especialistas, gestores públicos, economistas e membros da comunidade busca analisar e documentar atráves da produção de relatórios sobre a Coleta e Filtragem de Água na cidade de Caxias. Este evento busca promover a compreensão acerca da importância de estabelecer e partilhar dados estatíticos sobre o tema.');
INSERT INTO tb_event (project_id, user_id, event_date, created_date, event_status, image, title, description) VALUES (4, 3,   '2024-01-03',   now(),   'ADIADO',       'https://cdn1.iconfinder.com/data/icons/business-vivid-vol-2/256/Seminar-1024.png',                                        'Seminário sobre a expansão da Arquitetura Sustentável e Acessível em Caxias', 'O evento "Seminário sobre a expansão da Arquitetura Sustentável e Acessível em Caxias" trata-se de um seminário sobre a Arquitetura Sustentável e Acessível em Caxias. O Evento reunirá especialistas, arquitetos e urbanistas locais, residentes nos bairros envolvidos e interessados na temática para discutir as práticas e políticas acerca do assunto. Será uma oportunidade para aprender, trocar experiências e buscar soluções inovadoras.');
INSERT INTO tb_event (project_id, user_id, event_date, created_date, event_status, image, title, description) VALUES (4, 3,   '2024-01-09',   now(),   'FINALIZADO',   'https://cdn2.iconfinder.com/data/icons/career-advancement-4/512/Practice-1024.png',                                       'Atividade prática sobre uso de material reciclado para uma Arquitetura Sustentável e Acessível em Caxias', 'O evento "Atividade prática sobre uso de material reciclado para uma Arquitetura Sustentável e Acessível em Caxias" é uma iniciativa que visa implementar medidas práticas e técnicas em benefício da Arquitetura Sustentável e Acessível em Caxias. Este evento prático reunirá moradores do bairro para colaborar nos processos práticos que promoverão a integração social, a educação técnica e a multidisciplinaridade.');
INSERT INTO tb_event (project_id, user_id, event_date, created_date, event_status, image, title, description) VALUES (3, 4,   '2024-02-15',   now(),   'FINALIZADO',   'https://cdn2.iconfinder.com/data/icons/system-filled-outline/64/warning-danger-system-icon-512.png',                  'Palestra sobre os risco da falta de Reflorestamento em Caxias', 'O evento "Palestra 1 sobre os risco da falta de Reflorestamento em Caxias" é uma iniciativa educativa voltada para os moradores que desejam aprender mais sobre detalhes sobre a nescessidade do Reflorestamento. Este evento visa fornecer conhecimentos práticos e teóricos, concientizando os participantes da importância do Reflorestamento.');
INSERT INTO tb_event (project_id, user_id, event_date, created_date, event_status, image, title, description) VALUES (3, 4,   '2024-03-11',   now(),   'FINALIZADO',   'https://cdn-icons-png.flaticon.com/512/9912/9912471.png',                                                             'Debate dos dados periódicos sobre o Reflorestamento em áreas queimadas em Caxias', 'O evento "Debate dos dados periódicos sobre o Reflorestamento em áreas queimadas em Caxias" é uma oportunidade para os moradores, gestores públicos e interessados se reunirem para analisar e discutir os dados mais recentes sobre o desenvolvimento sobre o Reflorestamento na cidade. Este evento visa promover a transparência, a participação comunitária e a tomada de decisões informadas com base em dados concretos.');
INSERT INTO tb_event (project_id, user_id, event_date, created_date, event_status, image, title, description) VALUES (5, 5,   '2024-04-18',   now(),   'FINALIZADO',   'https://cdn0.iconfinder.com/data/icons/smart-technology-malibu-volume-1/128/intelligent-power-512.png',               'Criação de soluções 1 sobre a Reurbanização em Caxias', 'O evento "Criação de soluções 1 sobre a Reurbanização em Caxias" objetiva reunir especialistas, moradores e entusiastas da inovação para discutir e desenvolver soluções inovadoras em prol da Reurbanização . Este evento busca promover a adoção de novas ideias que foquem na eficiência e praticidade.');
INSERT INTO tb_event (project_id, user_id, event_date, created_date, event_status, image, title, description) VALUES (5, 5,   '2024-05-12',   now(),   'FINALIZADO',   'https://cdn-icons-png.flaticon.com/512/4730/4730760.png',                                                             'Videoconfêrencia sobre a reurbanização em bairros periféricos em Caxias', 'O evento "Videoconfêrencia sobre a Reurbanização em bairros periféricos em Caxias" promove o compartilhamento de conhecimentos e práticas sobre a Reurbanização . Este evento online reunirá especialistas, moradores urbanos e interessados para discutir técnicas, desafios e inovações');
INSERT INTO tb_event (project_id, user_id, event_date, created_date, event_status, image, title, description) VALUES (6, 6,   '2024-06-20',   now(),   'INDEFINIDO',   'https://cdn0.iconfinder.com/data/icons/business-situations-flat-1/64/annual-report-graph-summary-company-1024.png',   'Produção de relatórios sobre os avanços na Preservação de Barirros Históricos em Caxias', 'O evento "Produção de relatórios sobre os avanços na Preservação de Barirros Históricos em Caxias" que conta com a participação de especialistas, gestores públicos, economistas e membros da comunidade busca analisar e documentar atráves da produção de relatórios sobre a Preservação de Barirros Históricos na cidade de Caxias. Este evento busca promover a compreensão acerca da importância de estabelecer e partilhar dados estatíticos sobre o tema.');
INSERT INTO tb_event (project_id, user_id, event_date, created_date, event_status, image, title, description) VALUES (6, 3,   '2024-01-03',   now(),   'INDEFINIDO',   'https://cdn1.iconfinder.com/data/icons/business-vivid-vol-2/256/Seminar-1024.png',                                        'Seminário sobre inovações na arquitetura para a Preservação de Bairros Históricos em Caxias', 'O evento "Seminário 1 sobre a Preservação de Bairros Históricos em Caxias" trata-se de um seminário sobre a Preservação de Barirros Históricos em Caxias. O Evento reunirá especialistas, residentes nos bairros envolvidos e interessados na temática para discutir as práticas e políticas acerca do assunto. Será uma oportunidade para aprender, trocar experiências e buscar soluções inovadoras.');
INSERT INTO tb_event (project_id, user_id, event_date, created_date, event_status, image, title, description) VALUES (7, 3,   '2024-01-09',   now(),   'INDEFINIDO',   'https://cdn2.iconfinder.com/data/icons/career-advancement-4/512/Practice-1024.png',                                       'Atividade prática 1 sobre o Desenvolvimento Cultural em Caxias', 'O evento "Atividade prática 1 sobre o Desenvolvimento Cultural em Caxias" é uma iniciativa que visa implementar medidas práticas e técnicas em benefício do Desenvolvimento Cultural em Caxias. Este evento prático reunirá moradores do bairro para colaborar nos processos práticos que promoverão a integração social, a educação técnica e a multidisciplinaridade.');
INSERT INTO tb_event (project_id, user_id, event_date, created_date, event_status, image, title, description) VALUES (7, 4,   '2024-02-15',   now(),   'CANCELADO',    'https://cdn2.iconfinder.com/data/icons/system-filled-outline/64/warning-danger-system-icon-512.png',                  'Palestra sobre a importância Desenvolvimento do Cultural em Caxias', 'O evento "Palestra sobre a importância do Desenvolvimento Cultural em Caxias" é uma iniciativa educativa voltada para os moradores que desejam aprender mais sobre detalhes sobre o Desenvolvimento Cultural. Este evento visa fornecer conhecimentos práticos e teóricos, concientizando os participantes da importância do Desenvolvimento Cultural.');
INSERT INTO tb_event (project_id, user_id, event_date, created_date, event_status, image, title, description) VALUES (10, 4,  '2024-03-11',   now(),   'INDEFINIDO',   'https://cdn-icons-png.flaticon.com/512/9912/9912471.png',                                                            'Apresentação e debate dos dados periódicos 1 sobre Energias Renováveis em Caxias', 'O evento "Apresentação e debate dos dados periódicos 1 sobre as Energias Renováveis em Caxias" é uma oportunidade para os moradores, gestores públicos e interessados se reunirem para analisar e discutir os dados mais recentes sobre o desenvolvimento sobre as Energias Renováveis na cidade. Este evento visa promover a transparência, a participação comunitária e a tomada de decisões informadas com base em dados concretos.');
INSERT INTO tb_event (project_id, user_id, event_date, created_date, event_status, image, title, description) VALUES (10, 5,  '2024-04-18',   now(),   'FINALIZADO',   'https://cdn0.iconfinder.com/data/icons/smart-technology-malibu-volume-1/128/intelligent-power-512.png',              'Criação de soluções de acessibilidade para as Energias Renováveis em Caxias', 'O evento "Criação de soluções  de acessibilidade para as Energias Renováveis em Caxias" objetiva reunir especialistas, moradores e entusiastas da inovação para discutir e desenvolver soluções inovadoras em prol das Energias Renováveis. Este evento busca promover a adoção de novas ideias que foquem na eficiência e praticidade.');
INSERT INTO tb_event (project_id, user_id, event_date, created_date, event_status, image, title, description) VALUES (8, 5,   '2024-05-12',   now(),   'FINALIZADO',   'https://cdn-icons-png.flaticon.com/512/4730/4730760.png',                                                             'Videoconfêrencia a História da Economia da Cidade de Caxias', 'O evento "Videoconfêrencia 1 sobre a História da Cidade de Caxias" promove o compartilhamento de conhecimentos e práticas sobre a História da Cidade. Este evento online reunirá especialistas, moradores urbanos e interessados para discutir técnicas, desafios e inovações');
INSERT INTO tb_event (project_id, user_id, event_date, created_date, event_status, image, title, description) VALUES (8, 6,   '2024-06-20',   now(),   'FINALIZADO',   'https://cdn0.iconfinder.com/data/icons/business-situations-flat-1/64/annual-report-graph-summary-company-1024.png',   'Produção de relatórios 1 sobre a História da Cidade de Caxias', 'O evento "Produção de relatórios 1 sobre a História da Cidade de Caxias" que conta com a participação de especialistas, gestores públicos, economistas e membros da comunidade busca analisar e documentar atráves da produção de relatórios sobre a História da Cidade de Caxias. Este evento busca promover a compreensão acerca da importância de estabelecer e partilhar dados estatíticos sobre o tema.');

INSERT INTO tb_post (user_id, created_date, image, title, summary, description) VALUES (1, now(),'https://massanews.com/wp-content/uploads/2023/01/horta-comunitaria-cic.jpg','Seminário sobre Distribuição de Alimentos e Criação de Hortas Comunitárias em Agrobairros',                     'O projeto Agrobairros foi mais uma vez agraciado com dois importantes eventos, um seminário sobre distribuição de alimentos e uma atividade prática envolvendo o plantio de hostas comunitárias nos bairros. A iniciativa enaltece a integração social e a conscientização da colaboração comunitária',  'A cidade de Caxias foi palco de dois eventos significativos que destacaram a importância da agricultura urbana e da sustentabilidade: o “Seminário sobre a Distribuição de Alimentos nos Agrobairros” e a “Criação de Hortas Comunitárias no Bairro”. Ambos os eventos foram marcados por uma forte participação comunitária e resultados promissores para o futuro dos Agrobairros. O Seminário reuniu especialistas, gestores públicos e moradores para discutir estratégias eficientes de distribuição de alimentos produzidos nos Agrobairros. As atividades incluíram palestras informativas, painéis de debate e workshops práticos. O evento de atividade prática na criação de hortas comunitárias nos bairros contou com a participação entusiástica de moradores de todas as idades. A iniciativa visou transformar espaços urbanos subutilizados em hortas produtivas, promovendo a integração social e a educação ambiental.')
INSERT INTO tb_post (user_id, created_date, image, title, summary, description) VALUES (2, now(),'https://brcooperativo.com.br/wp-content/uploads/2022/11/reflorestamento.jpg','Os Riscos da Falta de Reflorestamento e Soluções para a Coleta e Filtragem de Água dos Rios',                  'Caxias sediou dois eventos importantes focados em questões ambientais: uma palestra sobre os riscos da falta de reflorestamento e um workshop sobre a criação de soluções para a coleta e filtragem de água dos rios.',  'A palestra destacou a importância do reflorestamento como uma estratégia crucial para combater as mudanças climáticas e preservar a biodiversidade da cidade de Caxias. Especialistas discutiram os impactos negativos do desmatamento, como a perda de habitat para espécies nativas e o aumento das emissões de gases de efeito estufa. O workshop focou em desenvolver tecnologias sustentáveis para a coleta e filtragem de água dos rios de Caxias, em especial o rio Itapecuru, visando melhorar a qualidade da água e garantir o abastecimento em áreas urbanas e rurais. Os resultados obtidos foram a prototipagem, com o desenvolvimento de protótipos de sistemas de coleta e filtragem de água. E também o estabelecimento de parcerias entre universidades e empresas para implementar as soluções desenvolvidas. Esses eventos foram fundamentais para promover a conscientização e a ação em prol da sustentabilidade ambiental, envolvendo diversos setores da sociedade em soluções práticas e inovadoras.')
INSERT INTO tb_post (user_id, created_date, image, title, summary, description) VALUES (3, now(),'https://www.drevostavitel.cz/galerie/clanky/2075/gallery/kontejnerove-domy-57635.jpg','Expansão da Arquitetura Sustentável e Acessível e Reurbanização em Bairros Periféricos em Caxias',    'Os dois eventos frizaram questões de moradia e infraestrutura: uma seminário sobre a expansão da arquitetura sustentável e acessível e uma videoconferência sobre a reurbanização em bairros periféricos em Caxias.',  'O evento focado na expansão da arquitetura sustentável e acessível, destacou a importância de criar espaços que sejam ecologicamente responsáveis e inclusivos para todos os usuários. As atividades envolvidas tiveram a participação de especialistas em arquitetura e sustentabilidade apresentaram os princípios da arquitetura sustentável e acessível, incluindo o uso de materiais ecológicos e a implementação de soluções que eliminem barreiras físicas. O evento com videoconferência foi realizada para discutir a reurbanização de bairros periféricos em Caxias, abordando os desafios e as soluções para melhorar a infraestrutura e a qualidade de vida nessas áreas. nas atividades envolvidas foram feitos painéis de Discussão com especialistas em urbanismo e representantes do governo discutiram políticas públicas e estratégias de reurbanização em Caxias.')
INSERT INTO tb_post (user_id, created_date, image, title, summary, description) VALUES (4, now(),'https://img.freepik.com/fotos-premium/relogio-de-bolso-vintage-fundo-vintage-conceito-de-historia-do-tempo_564276-1815.jpg','Avanços na Preservação de Bairros Históricos e  a Importância do Desenvolvimento Cultural em Caxias',                                             'Os eventos comtemplaram aspectos da cultura e história de Caxias sobre os avanços na preservação de bairros históricos e a importância do desenvolvimento cultural e uma videoconferência sobre a reurbanização em bairros periféricos em Caxias.',  'Recentemente, Caxias sediou um evento focado na produção de relatórios sobre a preservação de seus bairros históricos. Este evento reuniu especialistas e membros da comunidade para discutir e documentar estratégias de conservação. Outro evento significativo foi a palestra sobre a importância do desenvolvimento cultural em Caxias, que destacou como a cultura pode ser um motor de desenvolvimento social e econômico.')
INSERT INTO tb_post (user_id, created_date, image, title, summary, description) VALUES (9, now(),'https://tec.mx/sites/default/files/styles/header_full/public/2021-02/top-energy-una-alternativa-en-energias-verdes.jpg?h=920929c4&itok=wPnRvFyV','Soluções de acessibilidade para as Energias Renováveis e soluções para automatizar a produção de alimentos nos Agrobairros', 'Nesta semana, Caxias sediou dois eventos inovadores focados na criação de soluções de acessibilidade para as energias renováveis e para a automatizar a produção de alimentos nos agrobairros.',  'O de acessibilidade a energias renováveis reuniu especialistas, engenheiros e membros da comunidade para discutir e desenvolver tecnologias que tornem as energias limpas mais acessíveis a todos. Algumas das atividades envolvidas foram workshops práticos, onde Participantes receberam orientaçõees técnicas sobre a instalação e manutenção de sistemas de energia solar e eólica, além de técnicas para reduzir custos e aumentar a eficiência. E também houveram sessões de planejamento focadas em planos de ação que visam implementar soluções de energia renovável em comunidades de baixa renda. No evento de Agrobairros,  Foram realizadas demonstrações de tecnologias como drones, sensores IoT e sistemas de irrigação automatizados, que ajudam a monitorar e otimizar a produção agrícola e também grupos de trabalho discutiram estratégias para integrar essas tecnologias nas práticas agrícolas diárias. Os resultados obtidos foram Foram elaboradas propostas para políticas públicas que incentivem a adoção de energias renováveis em comunidades carentes e tecnologias que aumentaram a produtividade agrícola e reduziram o desperdício de recursos.')
INSERT INTO tb_post (user_id, created_date, image, title, summary, description) VALUES (10, now(),'https://wallpaperboat.com/wp-content/uploads/2020/12/14/63668/presentation-economy-11.jpg','História: como economia da cidade de Caxias evoluiu ?',                                                                               'A videoconferência explorou a rica história econômica da cidade. Este evento reuniu historiadores, economistas, estudantes e membros da comunidade para discutir e refletir sobre os principais marcos e transformações econômicas que moldaram Caxias.',  'Os especialistas em história econômica apresentaram palestras detalhadas sobre os períodos mais significativos da economia de Caxias, desde a era colonial até os dias atuais. Foram abordados temas como a agricultura, a industrialização e o comércio local. Após as palestras, houve sessões de debates onde os participantes puderam fazer perguntas e discutir as implicações das mudanças econômicas para o futuro da cidade. Foram apresentados estudos de caso de empresas e iniciativas locais que contribuíram para o desenvolvimento econômico de Caxias, destacando estratégias bem-sucedidas e lições aprendidas.  Os participantes tiveram a oportunidade de interagir diretamente com os palestrantes, fazendo perguntas e compartilhando suas próprias experiências e perspectivas sobre a economia local. A videoconferência aumentou a conscientização sobre a importância de entender a história econômica de Caxias para planejar seu futuro de forma mais informada e estratégica. O evento promoveu um maior engajamento da comunidade local, incentivando a participação ativa em discussões sobre desenvolvimento econômico.')
INSERT INTO tb_post (user_id, created_date, image, title, summary, description) VALUES (11, now(),'https://static.ndmais.com.br/2015/10/19-10-2015-18-35-42-professores-e-alunos-constroem-casa-com-mil-garrafas-pet-2757-1-.jpg','Sustentabilidade: o uso de material reciclado para uma arquitetura acessível em Caxias',          'O inovador evento focado na utilização de materiais reciclados para promover uma arquitetura sustentável e acessível. Este evento reuniu arquitetos, engenheiros, estudantes e membros da comunidade para explorar e implementar práticas de construção ecológicas e inclusivas.',  'Durante o evento, os participantes se envolveram em workshops onde aprenderam a utilizar materiais reciclados, como madeira reaproveitada, plásticos reciclados e outros resíduos de construção. Técnicas de construção sustentável foram demonstradas, incluindo a criação de estruturas modulares e o uso de materiais locais para reduzir a pegada de carbono. Também houveram grupos de trabalho colaboraram para desenvolver planos de ação que visam implementar essas práticas em projetos futuros na cidade. Foram discutidas estratégias para integrar a sustentabilidade e a acessibilidade em novos empreendimentos e reformas. Entres os participantes haviam universitários de cursos de arquitetura e engenharia, que participaram ativamente, aplicando os conceitos aprendidos em atividades práticas. Os moradores de Caxias, incluindo líderes comunitários e representantes de ONGs, participaram para entender como essas práticas podem ser aplicadas em suas comunidades. Ao fim do evento, foram desenvolvidos protótipos de pequenas estruturas utilizando materiais reciclados, demonstrando a viabilidade e os benefícios dessas técnicas.')
INSERT INTO tb_post (user_id, created_date, image, title, summary, description) VALUES (12, now(),'https://amazoniareal.com.br/wp-content/uploads/2016/12/SLIDE-QUEIMADAS-PARA-DESMATAMENTO-AMAZONIA_FOTO-RODRIGO-BALEIA-GREENPEACE-1024x683.jpg','Meio Ambiente: dados sobre o reflorestamento em áreas queimadas em Caxias',       'Caxias apresentou um evento focado no debate dos dados sobre o reflorestamento em áreas queimadas. Este evento reuniu especialistas em meio ambiente e membros da comunidade para discutir os desafios e progressos no reflorestamento.', 'O evento contou com a presença de pesquisadores apresentaram dados atualizados sobre as áreas queimadas, incluindo a extensão dos danos e as espécies de plantas mais afetadas. Utilizando imagens de satélite e mapeamento geoespacial, foram mostrados os avanços no reflorestamento e as áreas que ainda necessitam de intervenção. Especialistas em ecologia e reflorestamento participaram de painéis de discussão, abordando temas como técnicas de reflorestamento, seleção de espécies nativas e estratégias para prevenir futuras queimadas. Foi criado um mapeamento detalhado das áreas queimadas e das regiões que já foram reflorestadas, facilitando o monitoramento contínuo e a avaliação do progresso. Este evento foi fundamental para promover a recuperação ambiental em Caxias, envolvendo diversos setores da sociedade em um esforço colaborativo para restaurar as áreas afetadas por queimadas e garantir um futuro mais sustentável para a região.')

INSERT INTO tb_post (user_id, created_date, image, title, summary, description) VALUES (1, now(),'https://massanews.com/wp-content/uploads/2023/01/horta-comunitaria-cic.jpg',                                                                      'Seminário sobre Distribuição de Alimentos e Criação de Hortas Comunitárias em Agrobairros 1',                     'O projeto Agrobairros foi mais uma vez agraciado com dois importantes eventos, um seminário sobre distribuição de alimentos e uma atividade prática envolvendo o plantio de hostas comunitárias nos bairros. A iniciativa enaltece a integração social e a conscientização da colaboração comunitária',  'A cidade de Caxias foi palco de dois eventos significativos que destacaram a importância da agricultura urbana e da sustentabilidade: o “Seminário sobre a Distribuição de Alimentos nos Agrobairros” e a “Criação de Hortas Comunitárias no Bairro”. Ambos os eventos foram marcados por uma forte participação comunitária e resultados promissores para o futuro dos Agrobairros. O Seminário reuniu especialistas, gestores públicos e moradores para discutir estratégias eficientes de distribuição de alimentos produzidos nos Agrobairros. As atividades incluíram palestras informativas, painéis de debate e workshops práticos. O evento de atividade prática na criação de hortas comunitárias nos bairros contou com a participação entusiástica de moradores de todas as idades. A iniciativa visou transformar espaços urbanos subutilizados em hortas produtivas, promovendo a integração social e a educação ambiental.')
INSERT INTO tb_post (user_id, created_date, image, title, summary, description) VALUES (2, now(),'https://brcooperativo.com.br/wp-content/uploads/2022/11/reflorestamento.jpg',                                                                     'Os Riscos da Falta de Reflorestamento e Soluções para a Coleta e Filtragem de Água dos Rios 1',                  'Caxias sediou dois eventos importantes focados em questões ambientais: uma palestra sobre os riscos da falta de reflorestamento e um workshop sobre a criação de soluções para a coleta e filtragem de água dos rios.',  'A palestra destacou a importância do reflorestamento como uma estratégia crucial para combater as mudanças climáticas e preservar a biodiversidade da cidade de Caxias. Especialistas discutiram os impactos negativos do desmatamento, como a perda de habitat para espécies nativas e o aumento das emissões de gases de efeito estufa. O workshop focou em desenvolver tecnologias sustentáveis para a coleta e filtragem de água dos rios de Caxias, em especial o rio Itapecuru, visando melhorar a qualidade da água e garantir o abastecimento em áreas urbanas e rurais. Os resultados obtidos foram a prototipagem, com o desenvolvimento de protótipos de sistemas de coleta e filtragem de água. E também o estabelecimento de parcerias entre universidades e empresas para implementar as soluções desenvolvidas. Esses eventos foram fundamentais para promover a conscientização e a ação em prol da sustentabilidade ambiental, envolvendo diversos setores da sociedade em soluções práticas e inovadoras.')
INSERT INTO tb_post (user_id, created_date, image, title, summary, description) VALUES (3, now(),'https://www.drevostavitel.cz/galerie/clanky/2075/gallery/kontejnerove-domy-57635.jpg',                                                            'Expansão da Arquitetura Sustentável e Acessível e Reurbanização em Bairros Periféricos em Caxias 1',    'Os dois eventos frizaram questões de moradia e infraestrutura: uma seminário sobre a expansão da arquitetura sustentável e acessível e uma videoconferência sobre a reurbanização em bairros periféricos em Caxias.',  'O evento focado na expansão da arquitetura sustentável e acessível, destacou a importância de criar espaços que sejam ecologicamente responsáveis e inclusivos para todos os usuários. As atividades envolvidas tiveram a participação de especialistas em arquitetura e sustentabilidade apresentaram os princípios da arquitetura sustentável e acessível, incluindo o uso de materiais ecológicos e a implementação de soluções que eliminem barreiras físicas. O evento com videoconferência foi realizada para discutir a reurbanização de bairros periféricos em Caxias, abordando os desafios e as soluções para melhorar a infraestrutura e a qualidade de vida nessas áreas. nas atividades envolvidas foram feitos painéis de Discussão com especialistas em urbanismo e representantes do governo discutiram políticas públicas e estratégias de reurbanização em Caxias.')
INSERT INTO tb_post (user_id, created_date, image, title, summary, description) VALUES (4, now(),'https://img.freepik.com/fotos-premium/relogio-de-bolso-vintage-fundo-vintage-conceito-de-historia-do-tempo_564276-1815.jpg',                      'Avanços na Preservação de Bairros Históricos e  a Importância do Desenvolvimento Cultural em Caxias 1',                                             'Os eventos comtemplaram aspectos da cultura e história de Caxias sobre os avanços na preservação de bairros históricos e a importância do desenvolvimento cultural e uma videoconferência sobre a reurbanização em bairros periféricos em Caxias.',  'Recentemente, Caxias sediou um evento focado na produção de relatórios sobre a preservação de seus bairros históricos. Este evento reuniu especialistas e membros da comunidade para discutir e documentar estratégias de conservação. Outro evento significativo foi a palestra sobre a importância do desenvolvimento cultural em Caxias, que destacou como a cultura pode ser um motor de desenvolvimento social e econômico.')
INSERT INTO tb_post (user_id, created_date, image, title, summary, description) VALUES (9, now(),'https://tec.mx/sites/default/files/styles/header_full/public/2021-02/top-energy-una-alternativa-en-energias-verdes.jpg?h=920929c4&itok=wPnRvFyV', 'Soluções de acessibilidade para as Energias Renováveis e soluções para automatizar a produção de alimentos nos Agrobairros 1', 'Nesta semana, Caxias sediou dois eventos inovadores focados na criação de soluções de acessibilidade para as energias renováveis e para a automatizar a produção de alimentos nos agrobairros.',  'O de acessibilidade a energias renováveis reuniu especialistas, engenheiros e membros da comunidade para discutir e desenvolver tecnologias que tornem as energias limpas mais acessíveis a todos. Algumas das atividades envolvidas foram workshops práticos, onde Participantes receberam orientaçõees técnicas sobre a instalação e manutenção de sistemas de energia solar e eólica, além de técnicas para reduzir custos e aumentar a eficiência. E também houveram sessões de planejamento focadas em planos de ação que visam implementar soluções de energia renovável em comunidades de baixa renda. No evento de Agrobairros,  Foram realizadas demonstrações de tecnologias como drones, sensores IoT e sistemas de irrigação automatizados, que ajudam a monitorar e otimizar a produção agrícola e também grupos de trabalho discutiram estratégias para integrar essas tecnologias nas práticas agrícolas diárias. Os resultados obtidos foram Foram elaboradas propostas para políticas públicas que incentivem a adoção de energias renováveis em comunidades carentes e tecnologias que aumentaram a produtividade agrícola e reduziram o desperdício de recursos.')
INSERT INTO tb_post (user_id, created_date, image, title, summary, description) VALUES (10, now(),'https://wallpaperboat.com/wp-content/uploads/2020/12/14/63668/presentation-economy-11.jpg',                                                      'História: como economia da cidade de Caxias evoluiu ? 1',                                                                               'A videoconferência explorou a rica história econômica da cidade. Este evento reuniu historiadores, economistas, estudantes e membros da comunidade para discutir e refletir sobre os principais marcos e transformações econômicas que moldaram Caxias.',  'Os especialistas em história econômica apresentaram palestras detalhadas sobre os períodos mais significativos da economia de Caxias, desde a era colonial até os dias atuais. Foram abordados temas como a agricultura, a industrialização e o comércio local. Após as palestras, houve sessões de debates onde os participantes puderam fazer perguntas e discutir as implicações das mudanças econômicas para o futuro da cidade. Foram apresentados estudos de caso de empresas e iniciativas locais que contribuíram para o desenvolvimento econômico de Caxias, destacando estratégias bem-sucedidas e lições aprendidas.  Os participantes tiveram a oportunidade de interagir diretamente com os palestrantes, fazendo perguntas e compartilhando suas próprias experiências e perspectivas sobre a economia local. A videoconferência aumentou a conscientização sobre a importância de entender a história econômica de Caxias para planejar seu futuro de forma mais informada e estratégica. O evento promoveu um maior engajamento da comunidade local, incentivando a participação ativa em discussões sobre desenvolvimento econômico.')
INSERT INTO tb_post (user_id, created_date, image, title, summary, description) VALUES (11, now(),'https://static.ndmais.com.br/2015/10/19-10-2015-18-35-42-professores-e-alunos-constroem-casa-com-mil-garrafas-pet-2757-1-.jpg',                  'Sustentabilidade: o uso de material reciclado para uma arquitetura acessível em Caxias 1',          'O inovador evento focado na utilização de materiais reciclados para promover uma arquitetura sustentável e acessível. Este evento reuniu arquitetos, engenheiros, estudantes e membros da comunidade para explorar e implementar práticas de construção ecológicas e inclusivas.',  'Durante o evento, os participantes se envolveram em workshops onde aprenderam a utilizar materiais reciclados, como madeira reaproveitada, plásticos reciclados e outros resíduos de construção. Técnicas de construção sustentável foram demonstradas, incluindo a criação de estruturas modulares e o uso de materiais locais para reduzir a pegada de carbono. Também houveram grupos de trabalho colaboraram para desenvolver planos de ação que visam implementar essas práticas em projetos futuros na cidade. Foram discutidas estratégias para integrar a sustentabilidade e a acessibilidade em novos empreendimentos e reformas. Entres os participantes haviam universitários de cursos de arquitetura e engenharia, que participaram ativamente, aplicando os conceitos aprendidos em atividades práticas. Os moradores de Caxias, incluindo líderes comunitários e representantes de ONGs, participaram para entender como essas práticas podem ser aplicadas em suas comunidades. Ao fim do evento, foram desenvolvidos protótipos de pequenas estruturas utilizando materiais reciclados, demonstrando a viabilidade e os benefícios dessas técnicas.')
INSERT INTO tb_post (user_id, created_date, image, title, summary, description) VALUES (12, now(),'https://amazoniareal.com.br/wp-content/uploads/2016/12/SLIDE-QUEIMADAS-PARA-DESMATAMENTO-AMAZONIA_FOTO-RODRIGO-BALEIA-GREENPEACE-1024x683.jpg',  'Meio Ambiente: dados sobre o reflorestamento em áreas queimadas em Caxias 1',       'Caxias apresentou um evento focado no debate dos dados sobre o reflorestamento em áreas queimadas. Este evento reuniu especialistas em meio ambiente e membros da comunidade para discutir os desafios e progressos no reflorestamento.', 'O evento contou com a presença de pesquisadores apresentaram dados atualizados sobre as áreas queimadas, incluindo a extensão dos danos e as espécies de plantas mais afetadas. Utilizando imagens de satélite e mapeamento geoespacial, foram mostrados os avanços no reflorestamento e as áreas que ainda necessitam de intervenção. Especialistas em ecologia e reflorestamento participaram de painéis de discussão, abordando temas como técnicas de reflorestamento, seleção de espécies nativas e estratégias para prevenir futuras queimadas. Foi criado um mapeamento detalhado das áreas queimadas e das regiões que já foram reflorestadas, facilitando o monitoramento contínuo e a avaliação do progresso. Este evento foi fundamental para promover a recuperação ambiental em Caxias, envolvendo diversos setores da sociedade em um esforço colaborativo para restaurar as áreas afetadas por queimadas e garantir um futuro mais sustentável para a região.')

INSERT INTO tb_post (user_id, created_date, image, title, summary, description) VALUES (1, now(),'https://massanews.com/wp-content/uploads/2023/01/horta-comunitaria-cic.jpg',                                                                      'Seminário sobre Distribuição de Alimentos e Criação de Hortas Comunitárias em Agrobairros 2',                     'O projeto Agrobairros foi mais uma vez agraciado com dois importantes eventos, um seminário sobre distribuição de alimentos e uma atividade prática envolvendo o plantio de hostas comunitárias nos bairros. A iniciativa enaltece a integração social e a conscientização da colaboração comunitária',  'A cidade de Caxias foi palco de dois eventos significativos que destacaram a importância da agricultura urbana e da sustentabilidade: o “Seminário sobre a Distribuição de Alimentos nos Agrobairros” e a “Criação de Hortas Comunitárias no Bairro”. Ambos os eventos foram marcados por uma forte participação comunitária e resultados promissores para o futuro dos Agrobairros. O Seminário reuniu especialistas, gestores públicos e moradores para discutir estratégias eficientes de distribuição de alimentos produzidos nos Agrobairros. As atividades incluíram palestras informativas, painéis de debate e workshops práticos. O evento de atividade prática na criação de hortas comunitárias nos bairros contou com a participação entusiástica de moradores de todas as idades. A iniciativa visou transformar espaços urbanos subutilizados em hortas produtivas, promovendo a integração social e a educação ambiental.')
INSERT INTO tb_post (user_id, created_date, image, title, summary, description) VALUES (2, now(),'https://brcooperativo.com.br/wp-content/uploads/2022/11/reflorestamento.jpg',                                                                     'Os Riscos da Falta de Reflorestamento e Soluções para a Coleta e Filtragem de Água dos Rios 2',                  'Caxias sediou dois eventos importantes focados em questões ambientais: uma palestra sobre os riscos da falta de reflorestamento e um workshop sobre a criação de soluções para a coleta e filtragem de água dos rios.',  'A palestra destacou a importância do reflorestamento como uma estratégia crucial para combater as mudanças climáticas e preservar a biodiversidade da cidade de Caxias. Especialistas discutiram os impactos negativos do desmatamento, como a perda de habitat para espécies nativas e o aumento das emissões de gases de efeito estufa. O workshop focou em desenvolver tecnologias sustentáveis para a coleta e filtragem de água dos rios de Caxias, em especial o rio Itapecuru, visando melhorar a qualidade da água e garantir o abastecimento em áreas urbanas e rurais. Os resultados obtidos foram a prototipagem, com o desenvolvimento de protótipos de sistemas de coleta e filtragem de água. E também o estabelecimento de parcerias entre universidades e empresas para implementar as soluções desenvolvidas. Esses eventos foram fundamentais para promover a conscientização e a ação em prol da sustentabilidade ambiental, envolvendo diversos setores da sociedade em soluções práticas e inovadoras.')
INSERT INTO tb_post (user_id, created_date, image, title, summary, description) VALUES (3, now(),'https://www.drevostavitel.cz/galerie/clanky/2075/gallery/kontejnerove-domy-57635.jpg',                                                            'Expansão da Arquitetura Sustentável e Acessível e Reurbanização em Bairros Periféricos em Caxias 2',    'Os dois eventos frizaram questões de moradia e infraestrutura: uma seminário sobre a expansão da arquitetura sustentável e acessível e uma videoconferência sobre a reurbanização em bairros periféricos em Caxias.',  'O evento focado na expansão da arquitetura sustentável e acessível, destacou a importância de criar espaços que sejam ecologicamente responsáveis e inclusivos para todos os usuários. As atividades envolvidas tiveram a participação de especialistas em arquitetura e sustentabilidade apresentaram os princípios da arquitetura sustentável e acessível, incluindo o uso de materiais ecológicos e a implementação de soluções que eliminem barreiras físicas. O evento com videoconferência foi realizada para discutir a reurbanização de bairros periféricos em Caxias, abordando os desafios e as soluções para melhorar a infraestrutura e a qualidade de vida nessas áreas. nas atividades envolvidas foram feitos painéis de Discussão com especialistas em urbanismo e representantes do governo discutiram políticas públicas e estratégias de reurbanização em Caxias.')
INSERT INTO tb_post (user_id, created_date, image, title, summary, description) VALUES (4, now(),'https://img.freepik.com/fotos-premium/relogio-de-bolso-vintage-fundo-vintage-conceito-de-historia-do-tempo_564276-1815.jpg',                      'Avanços na Preservação de Bairros Históricos e  a Importância do Desenvolvimento Cultural em Caxias 2',                                             'Os eventos comtemplaram aspectos da cultura e história de Caxias sobre os avanços na preservação de bairros históricos e a importância do desenvolvimento cultural e uma videoconferência sobre a reurbanização em bairros periféricos em Caxias.',  'Recentemente, Caxias sediou um evento focado na produção de relatórios sobre a preservação de seus bairros históricos. Este evento reuniu especialistas e membros da comunidade para discutir e documentar estratégias de conservação. Outro evento significativo foi a palestra sobre a importância do desenvolvimento cultural em Caxias, que destacou como a cultura pode ser um motor de desenvolvimento social e econômico.')
INSERT INTO tb_post (user_id, created_date, image, title, summary, description) VALUES (9, now(),'https://tec.mx/sites/default/files/styles/header_full/public/2021-02/top-energy-una-alternativa-en-energias-verdes.jpg?h=920929c4&itok=wPnRvFyV', 'Soluções de acessibilidade para as Energias Renováveis e soluções para automatizar a produção de alimentos nos Agrobairros 2', 'Nesta semana, Caxias sediou dois eventos inovadores focados na criação de soluções de acessibilidade para as energias renováveis e para a automatizar a produção de alimentos nos agrobairros.',  'O de acessibilidade a energias renováveis reuniu especialistas, engenheiros e membros da comunidade para discutir e desenvolver tecnologias que tornem as energias limpas mais acessíveis a todos. Algumas das atividades envolvidas foram workshops práticos, onde Participantes receberam orientaçõees técnicas sobre a instalação e manutenção de sistemas de energia solar e eólica, além de técnicas para reduzir custos e aumentar a eficiência. E também houveram sessões de planejamento focadas em planos de ação que visam implementar soluções de energia renovável em comunidades de baixa renda. No evento de Agrobairros,  Foram realizadas demonstrações de tecnologias como drones, sensores IoT e sistemas de irrigação automatizados, que ajudam a monitorar e otimizar a produção agrícola e também grupos de trabalho discutiram estratégias para integrar essas tecnologias nas práticas agrícolas diárias. Os resultados obtidos foram Foram elaboradas propostas para políticas públicas que incentivem a adoção de energias renováveis em comunidades carentes e tecnologias que aumentaram a produtividade agrícola e reduziram o desperdício de recursos.')
INSERT INTO tb_post (user_id, created_date, image, title, summary, description) VALUES (10, now(),'https://wallpaperboat.com/wp-content/uploads/2020/12/14/63668/presentation-economy-11.jpg',                                                      'História: como economia da cidade de Caxias evoluiu ? 2',                                                                               'A videoconferência explorou a rica história econômica da cidade. Este evento reuniu historiadores, economistas, estudantes e membros da comunidade para discutir e refletir sobre os principais marcos e transformações econômicas que moldaram Caxias.',  'Os especialistas em história econômica apresentaram palestras detalhadas sobre os períodos mais significativos da economia de Caxias, desde a era colonial até os dias atuais. Foram abordados temas como a agricultura, a industrialização e o comércio local. Após as palestras, houve sessões de debates onde os participantes puderam fazer perguntas e discutir as implicações das mudanças econômicas para o futuro da cidade. Foram apresentados estudos de caso de empresas e iniciativas locais que contribuíram para o desenvolvimento econômico de Caxias, destacando estratégias bem-sucedidas e lições aprendidas.  Os participantes tiveram a oportunidade de interagir diretamente com os palestrantes, fazendo perguntas e compartilhando suas próprias experiências e perspectivas sobre a economia local. A videoconferência aumentou a conscientização sobre a importância de entender a história econômica de Caxias para planejar seu futuro de forma mais informada e estratégica. O evento promoveu um maior engajamento da comunidade local, incentivando a participação ativa em discussões sobre desenvolvimento econômico.')
INSERT INTO tb_post (user_id, created_date, image, title, summary, description) VALUES (11, now(),'https://static.ndmais.com.br/2015/10/19-10-2015-18-35-42-professores-e-alunos-constroem-casa-com-mil-garrafas-pet-2757-1-.jpg',                  'Sustentabilidade: o uso de material reciclado para uma arquitetura acessível em Caxias 2',          'O inovador evento focado na utilização de materiais reciclados para promover uma arquitetura sustentável e acessível. Este evento reuniu arquitetos, engenheiros, estudantes e membros da comunidade para explorar e implementar práticas de construção ecológicas e inclusivas.',  'Durante o evento, os participantes se envolveram em workshops onde aprenderam a utilizar materiais reciclados, como madeira reaproveitada, plásticos reciclados e outros resíduos de construção. Técnicas de construção sustentável foram demonstradas, incluindo a criação de estruturas modulares e o uso de materiais locais para reduzir a pegada de carbono. Também houveram grupos de trabalho colaboraram para desenvolver planos de ação que visam implementar essas práticas em projetos futuros na cidade. Foram discutidas estratégias para integrar a sustentabilidade e a acessibilidade em novos empreendimentos e reformas. Entres os participantes haviam universitários de cursos de arquitetura e engenharia, que participaram ativamente, aplicando os conceitos aprendidos em atividades práticas. Os moradores de Caxias, incluindo líderes comunitários e representantes de ONGs, participaram para entender como essas práticas podem ser aplicadas em suas comunidades. Ao fim do evento, foram desenvolvidos protótipos de pequenas estruturas utilizando materiais reciclados, demonstrando a viabilidade e os benefícios dessas técnicas.')
INSERT INTO tb_post (user_id, created_date, image, title, summary, description) VALUES (12, now(),'https://amazoniareal.com.br/wp-content/uploads/2016/12/SLIDE-QUEIMADAS-PARA-DESMATAMENTO-AMAZONIA_FOTO-RODRIGO-BALEIA-GREENPEACE-1024x683.jpg',  'Meio Ambiente: dados sobre o reflorestamento em áreas queimadas em Caxias 2',       'Caxias apresentou um evento focado no debate dos dados sobre o reflorestamento em áreas queimadas. Este evento reuniu especialistas em meio ambiente e membros da comunidade para discutir os desafios e progressos no reflorestamento.', 'O evento contou com a presença de pesquisadores apresentaram dados atualizados sobre as áreas queimadas, incluindo a extensão dos danos e as espécies de plantas mais afetadas. Utilizando imagens de satélite e mapeamento geoespacial, foram mostrados os avanços no reflorestamento e as áreas que ainda necessitam de intervenção. Especialistas em ecologia e reflorestamento participaram de painéis de discussão, abordando temas como técnicas de reflorestamento, seleção de espécies nativas e estratégias para prevenir futuras queimadas. Foi criado um mapeamento detalhado das áreas queimadas e das regiões que já foram reflorestadas, facilitando o monitoramento contínuo e a avaliação do progresso. Este evento foi fundamental para promover a recuperação ambiental em Caxias, envolvendo diversos setores da sociedade em um esforço colaborativo para restaurar as áreas afetadas por queimadas e garantir um futuro mais sustentável para a região.')


INSERT INTO tb_item_details (id, type, description, project_id, user_id) VALUES (1, 'OBJETIVOS', 'Educação e Conscientização: Fornecer educação prática sobre agricultura urbana, hortas comunitárias e sustentabilidade para jovens e adultos.', 1, 30);
INSERT INTO tb_item_details (id, type, description, project_id, user_id) VALUES (2, 'OBJETIVOS', 'Sustentabilidade Ambiental: Reduzir a pegada de carbono associada ao transporte de alimentos e promover práticas agrícolas ecológicas que preservem os recursos naturais.', 1, 30);
INSERT INTO tb_item_details (id, type, description, project_id, user_id) VALUES (3, 'OBJETIVOS', 'Segurança Alimentar: Aumentar a produção local de alimentos frescos e saudáveis, reduzindo a dependência de produtos de outras regiões e fortalecendo a segurança alimentar.', 1, 30);
INSERT INTO tb_item_details (id, type, description, project_id, user_id) VALUES (4, 'ETAPAS', 'Identificação de Áreas Potenciais: Mapear e selecionar áreas urbanas apropriadas para a implementação de agrobairros, como terrenos baldios, parques subutilizados e espaços comunitários.', 1, 30);
INSERT INTO tb_item_details (id, type, description, project_id, user_id) VALUES (5, 'ETAPAS', 'Parcerias e Financiamento: Estabelecer colaborações com instituições educacionais, ONGs, empresas locais e órgãos governamentais para obter recursos financeiros e técnicos.', 1, 30);
INSERT INTO tb_item_details (id, type, description, project_id, user_id) VALUES (6, 'ETAPAS', 'Planejamento e Projeto: Desenvolver planos detalhados para cada agrobairro, incluindo layout das áreas de cultivo, sistemas de irrigação, infraestruturas de compostagem e espaços de convivência.', 1, 30);
INSERT INTO tb_item_details (id, type, description, project_id, user_id) VALUES (7, 'IMPACTO', 'Social: Fortalecimento da coesão social e criação de um senso de comunidade através da colaboração em projetos agrícolas.', 1, 30);
INSERT INTO tb_item_details (id, type, description, project_id, user_id) VALUES (8, 'IMPACTO', 'Econômico: Geração de renda e novas oportunidades de emprego para os moradores envolvidos na agricultura urbana.', 1, 30);
INSERT INTO tb_item_details (id, type, description, project_id, user_id) VALUES (9, 'IMPACTO', 'Educacional: Aumento do conhecimento sobre sustentabilidade e técnicas agrícolas entre os cidadãos, preparando-os para enfrentar os desafios ambientais do futuro.', 1, 30);


INSERT INTO tb_event_user (event_id, user_id) VALUES (1, 1);
INSERT INTO tb_event_user (event_id, user_id) VALUES (1, 2);
INSERT INTO tb_event_user (event_id, user_id) VALUES (1, 3);
INSERT INTO tb_event_user (event_id, user_id) VALUES (1, 4);
INSERT INTO tb_event_user (event_id, user_id) VALUES (1, 5);
INSERT INTO tb_event_user (event_id, user_id) VALUES (2, 6);
INSERT INTO tb_event_user (event_id, user_id) VALUES (2, 7);
INSERT INTO tb_event_user (event_id, user_id) VALUES (2, 8);
INSERT INTO tb_event_user (event_id, user_id) VALUES (2, 9);
INSERT INTO tb_event_user (event_id, user_id) VALUES (3, 1);
INSERT INTO tb_event_user (event_id, user_id) VALUES (3, 3);
INSERT INTO tb_event_user (event_id, user_id) VALUES (4, 6);
INSERT INTO tb_event_user (event_id, user_id) VALUES (4, 8);
INSERT INTO tb_event_user (event_id, user_id) VALUES (5, 14);
INSERT INTO tb_event_user (event_id, user_id) VALUES (5, 15);
INSERT INTO tb_event_user (event_id, user_id) VALUES (6, 16);
INSERT INTO tb_event_user (event_id, user_id) VALUES (6, 17);
INSERT INTO tb_event_user (event_id, user_id) VALUES (7, 18);

INSERT INTO tb_project_category (project_id, category_id) VALUES (1, 1);
INSERT INTO tb_project_category (project_id, category_id) VALUES (1, 2);
INSERT INTO tb_project_category (project_id, category_id) VALUES (1, 3);
INSERT INTO tb_project_category (project_id, category_id) VALUES (1, 4);
INSERT INTO tb_project_category (project_id, category_id) VALUES (2, 1);
INSERT INTO tb_project_category (project_id, category_id) VALUES (2, 7);
INSERT INTO tb_project_category (project_id, category_id) VALUES (2, 13);
INSERT INTO tb_project_category (project_id, category_id) VALUES (3, 1);
INSERT INTO tb_project_category (project_id, category_id) VALUES (3, 2);
INSERT INTO tb_project_category (project_id, category_id) VALUES (3, 3);
INSERT INTO tb_project_category (project_id, category_id) VALUES (4, 4);
INSERT INTO tb_project_category (project_id, category_id) VALUES (4, 5);
INSERT INTO tb_project_category (project_id, category_id) VALUES (4, 13);
INSERT INTO tb_project_category (project_id, category_id) VALUES (5, 14);


INSERT INTO tb_user_category (user_id, category_id) VALUES (1, 1);
INSERT INTO tb_user_category (user_id, category_id) VALUES (1, 2);
INSERT INTO tb_user_category (user_id, category_id) VALUES (1, 3);
INSERT INTO tb_user_category (user_id, category_id) VALUES (1, 5);
INSERT INTO tb_user_category (user_id, category_id) VALUES (2, 1);
INSERT INTO tb_user_category (user_id, category_id) VALUES (2, 5);
INSERT INTO tb_user_category (user_id, category_id) VALUES (2, 7);
INSERT INTO tb_user_category (user_id, category_id) VALUES (3, 2);
INSERT INTO tb_user_category (user_id, category_id) VALUES (3, 4);
INSERT INTO tb_user_category (user_id, category_id) VALUES (3, 5);
INSERT INTO tb_user_category (user_id, category_id) VALUES (4, 6);
INSERT INTO tb_user_category (user_id, category_id) VALUES (4, 7);
INSERT INTO tb_user_category (user_id, category_id) VALUES (4, 8);
INSERT INTO tb_user_category (user_id, category_id) VALUES (5, 8);
INSERT INTO tb_user_category (user_id, category_id) VALUES (5, 11);
INSERT INTO tb_user_category (user_id, category_id) VALUES (5, 12);
INSERT INTO tb_user_category (user_id, category_id) VALUES (6, 13);
INSERT INTO tb_user_category (user_id, category_id) VALUES (6, 14);
INSERT INTO tb_user_category (user_id, category_id) VALUES (7, 15);
INSERT INTO tb_user_category (user_id, category_id) VALUES (7, 16);

INSERT INTO tb_project_post (project_id, post_id) VALUES (1, 1);
INSERT INTO tb_project_post (project_id, post_id) VALUES (2, 2);
INSERT INTO tb_project_post (project_id, post_id) VALUES (3, 2);
INSERT INTO tb_project_post (project_id, post_id) VALUES (4, 3);
INSERT INTO tb_project_post (project_id, post_id) VALUES (5, 3);
INSERT INTO tb_project_post (project_id, post_id) VALUES (6, 4);
INSERT INTO tb_project_post (project_id, post_id) VALUES (7, 4);
INSERT INTO tb_project_post (project_id, post_id) VALUES (1, 5);
INSERT INTO tb_project_post (project_id, post_id) VALUES (10, 5);
INSERT INTO tb_project_post (project_id, post_id) VALUES (8, 6);
INSERT INTO tb_project_post (project_id, post_id) VALUES (4, 7);
INSERT INTO tb_project_post (project_id, post_id) VALUES (3, 8);
INSERT INTO tb_project_post (project_id, post_id) VALUES (1, 9);
INSERT INTO tb_project_post (project_id, post_id) VALUES (2, 10);
INSERT INTO tb_project_post (project_id, post_id) VALUES (3, 10);
INSERT INTO tb_project_post (project_id, post_id) VALUES (4, 11);
INSERT INTO tb_project_post (project_id, post_id) VALUES (5, 11);
INSERT INTO tb_project_post (project_id, post_id) VALUES (6, 12);
INSERT INTO tb_project_post (project_id, post_id) VALUES (7, 12);
INSERT INTO tb_project_post (project_id, post_id) VALUES (1, 13);
INSERT INTO tb_project_post (project_id, post_id) VALUES (10, 13);
INSERT INTO tb_project_post (project_id, post_id) VALUES (8, 14);
INSERT INTO tb_project_post (project_id, post_id) VALUES (4, 15);
INSERT INTO tb_project_post (project_id, post_id) VALUES (3, 16);
INSERT INTO tb_project_post (project_id, post_id) VALUES (1, 1);
INSERT INTO tb_project_post (project_id, post_id) VALUES (2, 2);
INSERT INTO tb_project_post (project_id, post_id) VALUES (3, 2);
INSERT INTO tb_project_post (project_id, post_id) VALUES (4, 3);
INSERT INTO tb_project_post (project_id, post_id) VALUES (5, 3);
INSERT INTO tb_project_post (project_id, post_id) VALUES (6, 4);
INSERT INTO tb_project_post (project_id, post_id) VALUES (7, 4);
INSERT INTO tb_project_post (project_id, post_id) VALUES (1, 5);
INSERT INTO tb_project_post (project_id, post_id) VALUES (10, 5);
INSERT INTO tb_project_post (project_id, post_id) VALUES (8, 6);
INSERT INTO tb_project_post (project_id, post_id) VALUES (4, 7);
INSERT INTO tb_project_post (project_id, post_id) VALUES (3, 8);

